Release/basket about us
mamont79/eCommerce-Application pull request #65
Opened 2023-09-18 12:16 UTC by mamont79

1. Issue ticket number and link: [Sprint 4](https://dalhoupavel.atlassian.net/jira/software/projects/SCRUM/boards/1);
2. Screenshot:
![image](https://github.com/mamont79/eCommerce-Application/assets/70911716/05e59c80-a9f3-40d1-8c84-bb5349b96f0b)

3. Done 18.09.2023;
4. Description of changes:
  - [x] 4_01: Add "Add to Cart" Button on Product Cards
  - [x] 4_02: Integrate Catalog Page with Commercetools API
  - [x] 4_03: Implement Efficient Loading of Products on Catalog
  - [x] 4_07: Add Product to Cart Functionality for Non-Duplicated
  - [x] 4_10: Fetch and Display Cart Items Using commercetools API
  - [x] 4_11: Modify Quantity of Products in Cart
  - [x] 4_12: Implement "Remove from Cart" Button
  - [x] 4_14: Display Message for Empty Shopping Cart
  - [x] 4_15: Add Catalog Link to Empty Cart Message
  - [x] 4_18: Implement "Clear Shopping Cart" Button
  - [x] 4-19: Craft a Detailed Team Description with Photos
  - [x] 4_20: Incorporate and Link RS School Logo on the About Us
  - [x] 4_21: Implement Routing and Browser Navigation to Basket
  - [x] 4_22: Implement Routing and Browser Navigation to About US
  - [x] 4_23: Implement a Basket Icon in Header Navigation
  - [x] 4_24: Implement About Us Page Icon in Header Navigation
  - [x] 4_25: Add cart page
  - [x] 4_08: Remove Product from Cart Functionality
  - [x] 4_13: Recalculate Total Cost Upon Cart Updates
  - [ ] 4_16: Implement Promo Code Application Feature
  - [ ] 4_17: Display Original and Discounted Prices After Promo
5. Сomments:

2023-09-21 06:07 UTC, AnnaIgnatova requested changes

2023-09-21 06:07 UTC, AnnaIgnatova commented on src/pages/aboutUs/TeamMemeberCardsList/index.tsx
> +      {TeamMemebersData.map((member) => {
don't start variable with uppercase

2023-09-21 06:07 UTC, AnnaIgnatova commented on src/pages/aboutUs/TeamMemeberCardsList/index.tsx
> +      {TeamMemebersData.map((member) => {
use destructuring for member

2023-09-21 06:07 UTC, AnnaIgnatova commented on src/pages/basket/cardsBlock/CartCard/components/TextBlock/index.tsx
> +/* eslint-disable no-console */
remove disable rules

2023-09-21 06:07 UTC, AnnaIgnatova commented on src/pages/basket/cardsBlock/CartCard/components/TextBlock/index.tsx
> +  console.log(title);
remove console.log

2023-09-21 06:07 UTC, AnnaIgnatova commented on src/pages/basket/cardsBlock/CartCard/index.tsx
> +        <StyledImgWrapper style={{ backgroundImage: `url(${imgUrl})` }} />
why you use styled component and styles

2023-09-21 06:07 UTC, AnnaIgnatova commented on src/pages/basket/cardsBlock/CartCard/index.tsx
> +        <StyledImgWrapper style={{ backgroundImage: `url(${imgUrl})` }} />
you need to pass prop to styled compoentn

2023-09-21 06:07 UTC, AnnaIgnatova commented on src/pages/basket/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
remove disable rules

2023-09-21 06:07 UTC, AnnaIgnatova commented on src/pages/basket/orderBlock/index.tsx
> +/* eslint-disable no-param-reassign */
remove disable rules

2023-09-21 06:07 UTC, AnnaIgnatova commented on src/pages/basket/orderBlock/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
remove disable rules

2023-09-21 06:07 UTC, AnnaIgnatova commented on src/pages/basket/orderBlock/index.tsx
> +      onSubmit={(values) => {
replace function to separate func

2023-09-21 06:07 UTC, AnnaIgnatova commented on src/pages/welcome/index.tsx
> +/* eslint-disable react-hooks/exhaustive-deps */
remove disable rules

2023-09-21 06:07 UTC, AnnaIgnatova commented on src/pages/welcome/index.tsx
> +  console.log(isAuth);
console.og

2023-09-24 05:09 UTC, m5production commented on src/pages/aboutUs/TeamMemberCard/MemberCardBody/style.ts
> +
It looks more clear for me and, especially when there are many styles code, easier to read.

2023-09-25 07:22 UTC, AnnaIgnatova approved these changes

2023-09-25 07:23 UTC, AnnaIgnatova commented
mission completed 🥳🥳

2023-09-27 08:09 UTC, merged